workflows:
  unity_ios_build:
    name: Unity iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Build.xcarchive archive

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Build.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ExportedIPA
    artifacts:
      - ExportedIPA/*.ipa
