workflows:
  unity_ios_unsigned_build:
    name: Unity iOS Unsigned Build
    environment:
      xcode: latest
    scripts:
      - name: Build app
        script: |
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -sdk iphoneos \
            -configuration Release \
            build

          mkdir Payload
          cp -R ~/Library/Developer/Xcode/DerivedData/Unity-iPhone*/Build/Products/Release-iphoneos/*.app Payload/

          zip -r UnsignedApp.ipa Payload
    artifacts:
      - UnsignedApp.ipa
